name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Clerk Authentication
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      # Convex
      CONVEX_DEPLOYMENT: ${{ secrets.CONVEX_DEPLOYMENT }}
      NEXT_PUBLIC_CONVEX_URL: ${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
      # Database
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      # App Config
      AUTH_TOKEN_SECRET: ${{ secrets.AUTH_TOKEN_SECRET }}
      NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
      NODE_ENV: "production"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint
